### ISSUE TITLE
ValueLifter GetVarPointer segmentation fault

### ISSUE THREAD

**Issue by Toizi** [lifting-bits/anvill#152]
Using the following as spec input for `anvill-decompile-json-11.0`, I'm getting a segmentation fault
```
#0  0x0000000000cf3690 in llvm::BasicBlock::getModule() const ()
#1  0x00000000005ff75d in llvm::BasicBlock::getModule (this=0x0) at /home/marius/Downloads/vcpkg_ubuntu-20.04_llvm-11_amd64/installed/x64-linux-rel/include/llvm/IR/BasicBlock.h:117
#2  remill::BuildPointerToOffset (ir=..., ptr=0x19c7af0, dest_elem_offset=4, dest_ptr_type_=0x19b5600) at /home/marius/dev/remill/lib/BC/Util.cpp:2166
#3  0x00000000005bf646 in anvill::ValueLifterImpl::GetVarPointer (this=<optimized out>, var_ea=<optimized out>, search_ea=<optimized out>, ent_lifter=..., opt_ptr_type=0x19b5600) at ../anvill/src/Lifters/ValueLifter.cpp:96
#4  0x00000000005bfc2d in anvill::ValueLifterImpl::TryGetPointerForAddress (this=0x19ad330, ea=4210732, ent_lifter=..., hinted_type=<optimized out>) at ../anvill/src/Lifters/ValueLifter.cpp:216
#5  0x00000000005bfe75 in anvill::ValueLifterImpl::GetPointer (this=0x19ad330, ea=4210732, ptr_type=0x19bad60, ent_lifter=..., loc_ea=0) at ../anvill/src/Lifters/ValueLifter.cpp:236
#6  0x00000000005df8a5 in anvill::RecoverEntityUseInformation::UpdateFunction (this=0x1b06bf8, function=..., uses=...) at ../libraries/anvill_passes/src/RecoverEntityUseInformation.cpp:155
#7  0x00000000005df3c6 in anvill::RecoverEntityUseInformation::Run (this=0x1b06b50, function=...) at ../libraries/anvill_passes/src/RecoverEntityUseInformation.cpp:51
#8  0x00000000005e0db9 in anvill::BaseFunctionPass<anvill::RecoverEntityUseInformation>::runOnFunction (this=0x1b06b50, function_=...) at ../libraries/anvill_passes/src/BaseFunctionPass.h:142
#9  0x0000000000dcfcb1 in llvm::FPPassManager::runOnFunction(llvm::Function&) ()
#10 0x0000000000dcf3f9 in llvm::legacy::FunctionPassManagerImpl::run(llvm::Function&) ()
#11 0x0000000000dd5e76 in llvm::legacy::FunctionPassManager::run(llvm::Function&) ()
#12 0x00000000005aa373 in anvill::OptimizeModule (lifter_context=..., arch=<optimized out>, program=..., module=..., options=...) at ../anvill/src/Optimize.cpp:127
#13 0x0000000000599dd0 in main (argc=1, argc@entry=5, argv=<optimized out>, argv@entry=0x7fffffffdcd8) at ../tools/decompile-json/src/main.cpp:725
#14 0x00007ffff7a590b3 in __libc_start_main (main=0x5990f0 <main(int, char**)>, argc=5, argv=0x7fffffffdcd8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdcc8) at ../csu/libc-start.c:308
#15 0x000000000059902e in _start () at ../tools/decompile-json/src/main.cpp:62
```

From what I can tell, this is not really dependent on the input as much as it is simply wrong llvm api usage/assumptions.

## Analysis
Here an `IRBuilder` is created from an llvm context.
https://github.com/lifting-bits/anvill/blob/1e8fb38881103e383355115dc685ed16c0561c3e/anvill/src/Lifters/ValueLifter.cpp#L82-L98
The constructor for the `IRBuilder` will call `IRBuilderBase`'s constructor, which is the following
```c++
IRBuilderBase(LLVMContext &context, MDNode *FPMathTag = nullptr,
              ArrayRef<OperandBundleDef> OpBundles = None)
    : Context(context), DefaultFPMathTag(FPMathTag), IsFPConstrained(false),
      DefaultConstrainedExcept(fp::ebStrict),
      DefaultConstrainedRounding(fp::rmDynamic),
      DefaultOperandBundles(OpBundles) {
  ClearInsertionPoint();
}

void ClearInsertionPoint() {
  BB = nullptr;
  InsertPt = BasicBlock::iterator();
}
```
So `BB` is set to a `nullptr`.
This `IRBuilder` will be passed to `remill::BuildPointerToOffset`, which immediately gets a handle to the `BB` and calls `getModule` on it.
https://github.com/lifting-bits/remill/blob/d93823cd7286cfdbcc7f6f3586a3235737eb8b0d/lib/BC/Util.cpp#L2160-L2161
```c++
const auto block = ir.GetInsertBlock();
const auto module = block->getModule();
```
`GetInsertBlock` just returns `BB`, which is a `nullptr` and inside `getModule` the pointer will be dereferenced.
Unsure if this should/can be fixed in remill. While the basic block is not really used in that function and could be replaced with a call to `ir.getContext()`, remill still needs to get the module from somewhere.

<details>
<summary>Json spec file</summary>

```json
{
  "arch": "amd64",
  "os": "linux",
  "functions": [
    {
      "address": 4198672,
      "return_address": {
        "memory": {
          "register": "RSP",
          "offset": 0
        },
        "type": "L"
      },
      "return_stack_pointer": {
        "register": "RSP",
        "offset": 8,
        "type": "L"
      },
      "return_values": [
        {
          "register": "AL",
          "type": "B"
        }
      ]
    }
  ],
  "variables": [
    {
      "address": 4210728,
      "type": "L"
    }
  ],
  "symbols": [
  ],
  "memory": [
    {
      "address": 4198672,
      "is_writeable": false,
      "is_executable": true,
      "data": "554889e5c745fc000000008b0425284040008945f88b04252c404000890425284040008b45f88904252c4040008b0425284040005dc3"
    },
    {
      "address": 4210728,
      "is_writeable": true,
      "is_executable": false,
      "data": "000000002a000000"
    }
  ],
  "stack": {
    "address": 87960931799040,
    "size": 24576,
    "start_offset": 4096
  }
}
```
</details>

**Comment by pgoodman** [comment]
Fixed in #213.
