### ISSUE TITLE
Assertion Fail on armv7

### ISSUE THREAD

**Issue by artemdinaburg** [lifting-bits/anvill#209]
The main set of test fails on the AnghaBench subset is from ARMv7 in a CallInst assertion:

```
anvill-decompile-json-11.0: /__w/cxx-common/cxx-common/vcpkg/buildtrees/llvm-11/src/org-11.0.1-a4cf4b25b4.clean/llvm/lib/IR/Instructions.cpp:450: void llvm::CallInst::init(llvm::FunctionType *, llvm::Value *, ArrayRef<llvm::Value *>, ArrayRef<llvm::OperandBundleDef>, const llvm::Twine &): Assertion `(Args.size() == FTy->getNumParams() || (FTy->isVarArg() && Args.size() > FTy->getNumParams())) && "Calling a function with bad signature!"' failed.
```

Attaching a minimal test case json. Some relevant backtrace:
```
#8  0x000000000060dea6 in llvm::IRBuilderBase::CreateCall (this=<optimized out>, Callee=..., Args=..., Name=..., 
    FPMathTag=0x0)
    at /home/artem/git/IRENE/binary-explorer-scripts/irene-build/download-cxx-common-latest/installed/x64-linux-rel/include/llvm/IR/IRBuilder.h:2356
#9  remill::InstructionLifter::LiftIntoBlock (this=0x1ac27d8, arch_inst=..., block=0x1bee500, state_ptr=0x1ac4c30, 
    is_delayed=<optimized out>) at ../lib/BC/InstructionLifter.cpp:191
#10 0x00000000005d4db4 in anvill::FunctionLifter::VisitInstruction (this=0x1ac2690, inst=..., block=0x1bee500)
    at ../anvill/src/Lifters/FunctionLifter.cpp:1000
#11 0x00000000005d5b7d in anvill::FunctionLifter::VisitInstructions (this=0x1ac2690, address=<optimized out>)
    at ../anvill/src/Lifters/FunctionLifter.cpp:1195
#12 0x00000000005d8452 in anvill::FunctionLifter::LiftFunction (this=0x1ac2690, decl=...)
    at ../anvill/src/Lifters/FunctionLifter.cpp:1705
#13 0x00000000005d87b5 in anvill::EntityLifter::LiftEntity (this=0x7fffffffdd20, decl=...)
    at ../anvill/src/Lifters/FunctionLifter.cpp:1768
#14 0x00000000005b65bf in main::$_1::operator() (this=<optimized out>, decl=0x7fffffffb570)
    at ../tools/decompile-json/src/main.cpp:1068
```

[input.json.gz](https://github.com/lifting-bits/anvill/files/6593125/input.json.gz)

**Comment by pgoodman** [comment]
Closing as this has been diagnosed as a Remill issue, and will be solved over there.
