### ISSUE TITLE
Segfault in PointerLifter

### ISSUE THREAD

**Issue by artemdinaburg** [lifting-bits/anvill#221]
Triggered on a few different inputs; this looks to be in Phi node folding?

```
==172196==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x0000021bdeb4 bp 0x7fff75b500e0 sp 0x7fff75b500e0 T0)
==172196==The signal is caused by a READ memory access.
==172196==Hint: address points to the zero page.
    #0 0x21bdeb4 in llvm::Value::getContext() const /home/artem/git/cxx-common/vcpkg/buildtrees/llvm-11/src/org-11.0.1-a4cf4b25b4.clean/llvm/lib/IR/Value.cpp:826:49
    #1 0xa36698 in llvm::IRBuilder<llvm::ConstantFolder, llvm::IRBuilderDefaultInserter>::IRBuilder(llvm::Instruction*, llvm::MDNode*, llvm::ArrayRef<llvm::OperandBundleDefT<llvm::Value*> >) /home/artem/git/cxx-common/llvm-11-asan/installed/x64-linux-asan/include/llvm/IR/IRBuilder.h:2603:27
    #2 0xa5cc30 in anvill::PointerLifter::visitPHINode(llvm::PHINode&) /home/artem/git/anvill/build-asan/../libraries/anvill_passes/src/BrightenPointerOperations.cpp:595:23
    #3 0xa6174e in llvm::InstVisitor<anvill::PointerLifter, std::pair<llvm::Value*, bool> >::visitPHI(llvm::PHINode&) /home/artem/git/cxx-common/llvm-11-asan/installed/x64-linux-asan/include/llvm/IR/Instruction.def:208:1
    #4 0xa6174e in llvm::InstVisitor<anvill::PointerLifter, std::pair<llvm::Value*, bool> >::visit(llvm::Instruction&) /home/artem/git/cxx-common/llvm-11-asan/installed/x64-linux-asan/include/llvm/IR/Instruction.def:208:1
    #5 0xa58f88 in llvm::InstVisitor<anvill::PointerLifter, std::pair<llvm::Value*, bool> >::visit(llvm::Instruction*) /home/artem/git/cxx-common/llvm-11-asan/installed/x64-linux-asan/include/llvm/IR/InstVisitor.h:112:41
    #6 0xa58f88 in anvill::PointerLifter::visitInferInst(llvm::Instruction*, llvm::Type*) /home/artem/git/anvill/build-asan/../libraries/anvill_passes/src/BrightenPointerOperations.cpp:94:24
    #7 0xa5cc66 in anvill::PointerLifter::visitPHINode(llvm::PHINode&) /home/artem/git/anvill/build-asan/../libraries/anvill_passes/src/BrightenPointerOperations.cpp:599:33
    #8 0xa6174e in llvm::InstVisitor<anvill::PointerLifter, std::pair<llvm::Value*, bool> >::visitPHI(llvm::PHINode&) /home/artem/git/cxx-common/llvm-11-asan/installed/x64-linux-asan/include/llvm/IR/Instruction.def:208:1
    #9 0xa6174e in llvm::InstVisitor<anvill::PointerLifter, std::pair<llvm::Value*, bool> >::visit(llvm::Instruction&) /home/artem/git/cxx-common/llvm-11-asan/installed/x64-linux-asan/include/llvm/IR/Instruction.def:208:1
    #10 0xa58f88 in llvm::InstVisitor<anvill::PointerLifter, std::pair<llvm::Value*, bool> >::visit(llvm::Instruction*) /home/artem/git/cxx-common/llvm-11-asan/installed/x64-linux-asan/include/llvm/IR/InstVisitor.h:112:41
    #11 0xa58f88 in anvill::PointerLifter::visitInferInst(llvm::Instruction*, llvm::Type*) /home/artem/git/anvill/build-asan/../libraries/anvill_passes/src/BrightenPointerOperations.cpp:94:24
    #12 0xa5e952 in anvill::PointerLifter::visitBinaryOperator(llvm::BinaryOperator&) /home/artem/git/anvill/build-asan/../libraries/anvill_passes/src/BrightenPointerOperations.cpp:823:33
    #13 0xa616da in llvm::InstVisitor<anvill::PointerLifter, std::pair<llvm::Value*, bool> >::visit(llvm::Instruction&) /home/artem/git/cxx-common/llvm-11-asan/installed/x64-linux-asan/include/llvm/IR/InstVisitor.h
    #14 0xa58f88 in llvm::InstVisitor<anvill::PointerLifter, std::pair<llvm::Value*, bool> >::visit(llvm::Instruction*) /home/artem/git/cxx-common/llvm-11-asan/installed/x64-linux-asan/include/llvm/IR/InstVisitor.h:112:41
    #15 0xa58f88 in anvill::PointerLifter::visitInferInst(llvm::Instruction*, llvm::Type*) /home/artem/git/anvill/build-asan/../libraries/anvill_passes/src/BrightenPointerOperations.cpp:94:24
    #16 0xa5c841 in anvill::PointerLifter::visitIntToPtrInst(llvm::IntToPtrInst&) /home/artem/git/anvill/build-asan/../libraries/anvill_passes/src/BrightenPointerOperations.cpp:566:30
    #17 0xa61854 in llvm::InstVisitor<anvill::PointerLifter, std::pair<llvm::Value*, bool> >::visitIntToPtr(llvm::IntToPtrInst&) /home/artem/git/cxx-common/llvm-11-asan/installed/x64-linux-asan/include/llvm/IR/Instruction.def:194:1
    #18 0xa61854 in llvm::InstVisitor<anvill::PointerLifter, std::pair<llvm::Value*, bool> >::visit(llvm::Instruction&) /home/artem/git/cxx-common/llvm-11-asan/installed/x64-linux-asan/include/llvm/IR/Instruction.def:194:1
    #19 0xa56faf in llvm::InstVisitor<anvill::PointerLifter, std::pair<llvm::Value*, bool> >::visit(llvm::Instruction*) /home/artem/git/cxx-common/llvm-11-asan/installed/x64-linux-asan/include/llvm/IR/InstVisitor.h:112:41
    #20 0xa56faf in anvill::PointerLifter::LiftFunction(llvm::Function&) /home/artem/git/anvill/build-asan/../libraries/anvill_passes/src/BrightenPointerOperations.cpp:1046:7
    #21 0xa566dc in anvill::PointerLifterPass::runOnFunction(llvm::Function&) /home/artem/git/anvill/build-asan/../libraries/anvill_passes/src/BrightenPointerOperations.cpp:46:10
    #22 0x20d185b in llvm::FPPassManager::runOnFunction(llvm::Function&) /home/artem/git/cxx-common/vcpkg/buildtrees/llvm-11/src/org-11.0.1-a4cf4b25b4.clean/llvm/lib/IR/LegacyPassManager.cpp:1516:27
    #23 0x20d1004 in llvm::legacy::FunctionPassManagerImpl::run(llvm::Function&) /home/artem/git/cxx-common/vcpkg/buildtrees/llvm-11/src/org-11.0.1-a4cf4b25b4.clean/llvm/lib/IR/LegacyPassManager.cpp:439:44
    #24 0x20d9e0c in llvm::legacy::FunctionPassManager::run(llvm::Function&) /home/artem/git/cxx-common/vcpkg/buildtrees/llvm-11/src/org-11.0.1-a4cf4b25b4.clean/llvm/lib/IR/LegacyPassManager.cpp:1435:15
    #25 0x9c3633 in anvill::OptimizeModule(anvill::EntityLifter const&, remill::Arch const*, anvill::Program const&, llvm::Module&, anvill::LifterOptions const&) /home/artem/git/anvill/build-asan/../anvill/src/Optimize.cpp:132:9
    #26 0x95ab10 in main /home/artem/git/anvill/build-asan/../tools/decompile-json/src/main.cpp:1093:3
    #27 0x7f7df4ee5d09 in __libc_start_main csu/../csu/libc-start.c:308:16
    #28 0x8ac0c9 in _start (/home/artem/git/anvill/build-asan/tools/decompile-json/anvill-decompile-json-11.0+0x8ac0c9)
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/artem/git/cxx-common/vcpkg/buildtrees/llvm-11/src/org-11.0.1-a4cf4b25b4.clean/llvm/lib/IR/Value.cpp:826:49 in llvm::Value::getContext() const
==172196==ABORTING
```

**Comment by kumarak** [comment]
The issue should get fixed with PR https://github.com/lifting-bits/anvill/pull/231
