### ISSUE TITLE
Binja frontend attempts to get value of LLIL virtual register

### ISSUE THREAD

**Issue by surovic** [lifting-bits/anvill#84]
Given a binary compiled from `tests/branch.c` via `clang-9.0` anvill's binja frontend crashes with 

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/my_user/.local/lib/python3.8/site-packages/anvill-1.0-py3.8.egg/anvill/__main__.py", line 77, in <module>
  File "/home/my_user/.local/lib/python3.8/site-packages/anvill-1.0-py3.8.egg/anvill/__main__.py", line 66, in main
  File "/home/my_user/.local/lib/python3.8/site-packages/anvill-1.0-py3.8.egg/anvill/program.py", line 97, in add_function_definition
  File "/home/my_user/.local/lib/python3.8/site-packages/anvill-1.0-py3.8.egg/anvill/binja.py", line 348, in visit
  File "/home/my_user/.local/lib/python3.8/site-packages/anvill-1.0-py3.8.egg/anvill/binja.py", line 398, in _extract_types
  File "/home/my_user/.local/lib/python3.8/site-packages/anvill-1.0-py3.8.egg/anvill/binja.py", line 405, in _extract_types
  File "/home/my_user/git/binaryninja/python/binaryninja/lowlevelil.py", line 1078, in get_reg_value
    reg = self._function.arch.get_reg_index(reg)
  File "/home/my_user/git/binaryninja/python/binaryninja/architecture.py", line 1564, in get_reg_index
    return self.regs[reg].index
KeyError: 'temp0'
```
This is likely due to `binaryninja.LowLevelILInstruction.get_reg_value()` being called on

```
temp0.q = divs.dp.q(rdx:rax, rcx)
```

where `temp0` is a virtual register as opposed to a real one like `rax` or `al`.

**Comment by surovic** [comment]
The same likely happens with `tests/assert.c` and `tests/sum.c`.

**Comment by kumarak** [comment]
@surovic, Can you test the issue again? It should be fixed with the latest changes.
