### ISSUE TITLE
ARM64 binaries make the frontend die on invalid references

### ISSUE THREAD

**Issue by artemdinaburg** [lifting-bits/anvill#93]
ARM64 binaries often reference data via a combination of `adrp` and `add` (or similar instructions). The initial reference via `adrp` is (correctly) detected as not present in the binary, and then Anvill (incorrectly) bails out in terror and abandons lifting.

Anvill should not abandon lifting, and `adrp`/`add` combination references should work in bitcode generated from ARM64 binaries.

Example output:

```artem@beefy:~/git/irene-temp-dev/anvill/temp$ python3 -m anvill --bin_in output.arm64.elf --spec_out arm64.json
Traceback (most recent call last):
  File "/home/artem/.local/lib/python3.9/site-packages/anvill-1.0-py3.9.egg/anvill/program.py", line 116, in try_add_referenced_entity
  File "/home/artem/.local/lib/python3.9/site-packages/anvill-1.0-py3.9.egg/anvill/program.py", line 90, in add_function_definition
  File "/home/artem/.local/lib/python3.9/site-packages/anvill-1.0-py3.9.egg/anvill/program.py", line 45, in get_function
  File "/home/artem/.local/lib/python3.9/site-packages/anvill-1.0-py3.9.egg/anvill/binja.py", line 484, in get_function_impl
anvill.exc.InvalidFunctionException: No function defined at or containing address 410000```

**Comment by artemdinaburg** [comment]
Fixed
